import sqlite3
from datetime import datetime

from app.config import load_config
from app.notifier import EmailNotifier


def get_summary(db_path):
    today = datetime.now().strftime("%Y-%m-%d")

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT COUNT(*) FROM events
        WHERE event_type='PERSON_ENTERED'
        AND event_time LIKE ?
        """,
        (today + "%",)
    )
    entries = cursor.fetchone()[0]

    cursor.execute(
        """
        SELECT COUNT(*) FROM events
        WHERE event_type='PERSON_EXITED'
        AND event_time LIKE ?
        """,
        (today + "%",)
    )
    exits = cursor.fetchone()[0]

    cursor.execute(
        """
        SELECT MIN(event_time) FROM events
        WHERE event_type='PERSON_ENTERED'
        AND event_time LIKE ?
        """,
        (today + "%",)
    )
    first_entry = cursor.fetchone()[0]

    cursor.execute(
        """
        SELECT MAX(event_time) FROM events
        WHERE event_type='PERSON_EXITED'
        AND event_time LIKE ?
        """,
        (today + "%",)
    )
    last_exit = cursor.fetchone()[0]

    cursor.execute(
        """
        SELECT event_time, event_type, image_path, email_sent
        FROM events
        WHERE event_time LIKE ?
        ORDER BY event_time DESC
        LIMIT 10
        """,
        (today + "%",)
    )
    recent_events = cursor.fetchall()

    conn.close()

    return {
        "date": today,
        "entries": entries,
        "exits": exits,
        "first_entry": first_entry,
        "last_exit": last_exit,
        "recent_events": recent_events
    }


def build_html_report(summary):
    rows = ""

    for event_time, event_type, image_path, email_sent in summary["recent_events"]:
        rows += f"""
        <tr>
            <td>{event_time}</td>
            <td>{event_type}</td>
            <td>{image_path}</td>
            <td>{'Yes' if email_sent == 1 else 'No'}</td>
        </tr>
        """

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; background-color: #f4f6f8; padding: 20px;">
        <div style="max-width: 750px; margin: auto; background: white; padding: 25px; border-radius: 10px;">
            <h2 style="color: #1f2937;">AI Server Room Daily Report</h2>

            <p style="color: #555;">
                Automated daily summary generated by the AI Server Room Monitoring System.
            </p>

            <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                <tr>
                    <td style="padding: 10px; border: 1px solid #ddd;"><b>Date</b></td>
                    <td style="padding: 10px; border: 1px solid #ddd;">{summary["date"]}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #ddd;"><b>Total Entries</b></td>
                    <td style="padding: 10px; border: 1px solid #ddd;">{summary["entries"]}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #ddd;"><b>Total Exits</b></td>
                    <td style="padding: 10px; border: 1px solid #ddd;">{summary["exits"]}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #ddd;"><b>First Entry</b></td>
                    <td style="padding: 10px; border: 1px solid #ddd;">{summary["first_entry"] or "N/A"}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #ddd;"><b>Last Exit</b></td>
                    <td style="padding: 10px; border: 1px solid #ddd;">{summary["last_exit"] or "N/A"}</td>
                </tr>
            </table>

            <h3 style="margin-top: 30px; color: #1f2937;">Recent Events</h3>

            <table style="width: 100%; border-collapse: collapse;">
                <tr style="background-color: #e5e7eb;">
                    <th style="padding: 10px; border: 1px solid #ddd;">Time</th>
                    <th style="padding: 10px; border: 1px solid #ddd;">Event</th>
                    <th style="padding: 10px; border: 1px solid #ddd;">Snapshot</th>
                    <th style="padding: 10px; border: 1px solid #ddd;">Email Sent</th>
                </tr>
                {rows if rows else '<tr><td colspan="4" style="padding:10px; border:1px solid #ddd;">No events today</td></tr>'}
            </table>

            <p style="margin-top: 30px; color: #777; font-size: 12px;">
                Generated automatically. Please do not reply to this email.
            </p>
        </div>
    </body>
    </html>
    """

    return html


def build_plain_text(summary):
    return f"""
AI Server Room Daily Report

Date: {summary["date"]}

Total Entries: {summary["entries"]}
Total Exits: {summary["exits"]}

First Entry: {summary["first_entry"] or "N/A"}
Last Exit: {summary["last_exit"] or "N/A"}

Generated automatically.
"""


def send_summary():
    config = load_config()

    summary = get_summary(config["storage"]["database_path"])

    notifier = EmailNotifier(config["smtp"])

    subject = f"[AI SUMMARY] Server Room Daily Report - {summary['date']}"

    html_body = build_html_report(summary)
    plain_text = build_plain_text(summary)

    notifier.send_html_email(
        subject=subject,
        html_body=html_body,
        plain_text_body=plain_text
    )

    print("[SUMMARY] Daily summary sent")


if __name__ == "__main__":
    send_summary()
